import test from 'node:test';
import assert from 'node:assert/strict';
import {mergeGalaxyLayout, fitGalaxyCamera} from '../ui/galaxy-logic.js';
import {placeGalaxyLabels, galaxyLabelCandidates} from '../ui/galaxy-labels.js';
import {createGalaxyLayoutSession} from '../ui/galaxy-layout-editor.js';
const parameters={n_neighbors:12,min_dist:.4,spread:1.5,repulsion_strength:2.5};
const layout=()=>({schema_version:1,cache_key:'old',metadata:{catalog_sha256:'catalog',model:'mpnet',embedding:{sha256:'sha',dtype:'float64',shape:[2,768],identity:'internal'}},topics:[{id:'A',x:0,y:0,neighbors:[{id:'B',distance:.2}]},{id:'B',x:1,y:1,neighbors:[{id:'A',distance:.2}]}],domains:[{id:'Science',x:.5,y:.5}]});
const result=()=>({schema_version:1,cache_key:'new',catalog_sha256:'catalog',model:'mpnet',embedding:{sha256:'sha',dtype:'float64',shape:[2,768]},parameters,topics:[{id:'B',x:8,y:9},{id:'A',x:4,y:5}],domains:[{id:'Science',x:6,y:7}]});
test('remote geometry merges by ID without altering original semantic neighbors',()=>{const original=layout(),merged=mergeGalaxyLayout(original,result(),parameters);assert.equal(merged.topics[0].x,4);assert.deepEqual(merged.topics[0].neighbors,original.topics[0].neighbors);assert.equal(original.topics[0].x,0);assert.equal(merged.metadata.embedding.identity,'internal');});
test('geometry rejects mismatch, duplicate/missing IDs and invalid coordinates or parameters',()=>{for(const mutate of [r=>r.catalog_sha256='other',r=>r.model='other',r=>r.embedding.sha256='other',r=>r.embedding.shape=[3,768],r=>r.parameters={...parameters,min_dist:.2},r=>r.topics[0].id='A',r=>r.topics.pop(),r=>r.topics[0].x=NaN,r=>r.domains[0].id='other',r=>r.domains.push({...r.domains[0]})]){const r=result();mutate(r);assert.throws(()=>mergeGalaxyLayout(layout(),r,parameters));}});
test('fit accommodates dense large bounds and narrow controls',()=>{const camera=fitGalaxyCamera({minX:-10,maxX:10,minY:-10,maxY:10},{width:320,height:390});assert.equal(camera.x,0);assert.ok(camera.zoom>0&&camera.zoom<1);});
test('label placement honors priority and exclusions and increases domain density with zoom',()=>{const labels=[{id:'domain',text:'Science',x:100,y:100,kind:'domain'},{id:'saved',text:'Saved',x:100,y:100,kind:'saved'},{id:'selected',text:'Chosen',x:100,y:100,kind:'selected'}];const placed=placeGalaxyLabels(labels,{width:320,height:390},s=>s.length*7,[{x:0,y:0,width:320,height:60}]);assert.equal(placed[0].id,'selected');for(let i=0;i<placed.length;i++){assert.ok(placed[i].box.y>=60);for(let j=0;j<i;j++){const a=placed[i].box,b=placed[j].box;assert.ok(a.x+a.width<=b.x||b.x+b.width<=a.x||a.y+a.height<=b.y||b.y+b.height<=a.y);}}const topics=[{id:'A',topic:'Alpha',domain:'S'}],data={topics,byId:new Map(topics.map(t=>[t.id,t])),domains:[{id:'S',x:10,y:10}]};const hidden=galaxyLabelCandidates(data,{selected:'A',camera:{zoom:1}}, {focus:'A',settings:{galaxyShowInterestLabels:false,galaxyShowDomainLabels:false}},new Set(['A']),new Set(),null);assert.deepEqual(hidden.map(l=>l.kind),['selected']);});
test('reset/invalidation prevents late remote result and cancels polling',async()=>{let resolve;const ready=new Promise(r=>resolve=r),seen=[];const session=createGalaxyLayoutSession({request:()=>ready,poll:()=>{},onReady:r=>seen.push(r),onChange:()=>{}});const pending=session.generate(parameters);session.invalidate();resolve({job_id:'old',status:'ready',result:result()});await pending;assert.equal(seen.length,0);assert.equal(session.getSnapshot().status,'idle');session.destroy();});
test('polling displays stages and only current ready result applies',async()=>{const changes=[],seen=[];let task;const session=createGalaxyLayoutSession({request:async()=>({job_id:'job',status:'queued',stage:'Starting'}),poll:async()=>({job_id:'job',status:'ready',result:result()}),onReady:(r,p)=>seen.push([r,p]),onChange:s=>changes.push(s),schedule:fn=>{task=fn;return 1;},cancel:()=>{}});await session.generate(parameters);assert.equal(session.getSnapshot().status,'queued');await task();assert.equal(seen.length,1);assert.deepEqual(seen[0][1],parameters);assert.equal(session.getSnapshot().status,'ready');session.destroy();});

test('new generation and destroy retire pending requests, failed jobs keep prior geometry',async()=>{
  const resolves=[],seen=[];const session=createGalaxyLayoutSession({request:()=>new Promise(r=>resolves.push(r)),poll:async()=>{},onReady:r=>seen.push(r)});
  const first=session.generate(parameters),second=session.generate({...parameters,n_neighbors:15});
  resolves[0]({job_id:'first',status:'ready',result:result()});await first;assert.equal(seen.length,0);
  resolves[1]({job_id:'second',status:'failed',error:'Unavailable'});await second;assert.equal(session.getSnapshot().status,'failed');assert.equal(seen.length,0);
  const third=session.generate(parameters);session.destroy();resolves[2]({job_id:'third',status:'ready',result:result()});await third;assert.equal(seen.length,0);
});
test('layout polling times out and malformed jobs fail without applying coordinates',async()=>{
  let task,time=0;const seen=[];const session=createGalaxyLayoutSession({request:async()=>({job_id:'job',status:'queued'}),poll:async()=>({job_id:'job',status:'ready',result:result()}),onReady:r=>seen.push(r),schedule:fn=>{task=fn;return 1;},cancel:()=>{},now:()=>time,timeout:100});
  await session.generate(parameters);time=101;await task();assert.equal(session.getSnapshot().status,'failed');assert.match(session.getSnapshot().error,/timed out/);assert.equal(seen.length,0);session.destroy();
  const invalid=createGalaxyLayoutSession({request:async()=>({job_id:'job',status:'unexpected'}),poll:async()=>{},onReady:r=>seen.push(r)});await invalid.generate(parameters);assert.equal(invalid.getSnapshot().status,'failed');assert.equal(seen.length,0);invalid.destroy();
});
